### ISSUE TITLE
Can't run mallet via python due to FileNotFoundError & CalledProcessError

### ISSUE THREAD

**Issue by bbiney1** [mimno/Mallet#135]
I'm using python 3 on windows 10 and I'm struggling to get mallet to work via python scripts as opposed to the command line.  I have been able to get mallet to run successfully through my git bash command line, it does seem to create an input and output file in my computer's default temp location, `C:\Users\biney\AppData\Local\Temp`. However, getting a python program to successfully run the `Ldamallet()` function is another story.

`from pathlib import Path`
`home = str(Path.home())`
`MALLET_BINARY_PATH = home + "\\mallet_unzipped\\mallet-2.0.8\\bin\\mallet"`
`#MALLET_BINARY_PATH ="/c/users/biney/mallet_unzipped/mallet-2.0.8/bin/mallet"` # something I've tried
`doc_term_matrix = [doc_dict.doc2bow(doc) for doc in docs_of_tokens]`
`Lda_mallet = LdaMallet(mallet_path=MALLET_BINARY_PATH,  corpus=doc_term_matrix, id2word=doc_dict, iterations=30)`

I'm getting slightly different error messages when I change the characters in `MALLET_BINARY_PATH` but I seem to be alternating between two error messages. Here's the first, when I run the code as is (with MALLET_BINARY_PATH set to "home + ..."  (this prints: C:\Users\biney\mallet_unzipped\mallet-2.0.8\bin\mallet)

```
Traceback (most recent call last):
  File "text_mining.py", line 632, in <module>
    main()
  File "text_mining.py", line 563, in main
    mallet_LDA_implementation(name_of_lda="mallet_lda_no_filter_t10", create_dic
t=False, remove_low_freq=False)
  File "text_mining.py", line 458, in mallet_LDA_implementation
    Lda_mallet = LdaMallet(mallet_path=MALLET_BINARY_PATH,  corpus=doc_term_matr
ix, id2word=doc_dict, iterations=30)
  File "C:\Users\biney\Miniconda3\lib\site-packages\gensim\models\wrappers\ldama
llet.py", line 126, in __init__
    self.train(corpus)
  File "C:\Users\biney\Miniconda3\lib\site-packages\gensim\models\wrappers\ldama
llet.py", line 279, in train
    self.word_topics = self.load_word_topics()
  File "C:\Users\biney\Miniconda3\lib\site-packages\gensim\models\wrappers\ldama
llet.py", line 337, in load_word_topics
    with utils.smart_open(self.fstate()) as fin:
  File "C:\Users\biney\Miniconda3\lib\site-packages\smart_open\smart_open_lib.py
", line 231, in smart_open
    binary, filename = _open_binary_stream(uri, binary_mode, **kw)
  File "C:\Users\biney\Miniconda3\lib\site-packages\smart_open\smart_open_lib.py
", line 318, in _open_binary_stream
    fobj = io.open(parsed_uri.uri_path, mode)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\biney\\AppDa
ta\\Local\\Temp\\db41f1_state.mallet.gz'
```
It seems like what's problematic about this error message is the two backslashes used between directories. However, the way I've been typing in backslashes into python is through the following: `'\\'` and it's at least printing correctly.
If I comment out the `MALLET_BINARY_PATH = home +...` and comment in the line below it, I get the following error message:

```
Traceback (most recent call last):
  File "text_mining.py", line 632, in <module>
    main()
  File "text_mining.py", line 563, in main
    mallet_LDA_implementation(name_of_lda="mallet_lda_no_filter_t10", create_dic
t=False, remove_low_freq=False)
  File "text_mining.py", line 458, in mallet_LDA_implementation
    Lda_mallet = LdaMallet(mallet_path=MALLET_BINARY_PATH,  corpus=doc_term_matr
ix, id2word=doc_dict, iterations=30)
  File "C:\Users\biney\Miniconda3\lib\site-packages\gensim\models\wrappers\ldama
llet.py", line 126, in __init__
    self.train(corpus)
  File "C:\Users\biney\Miniconda3\lib\site-packages\gensim\models\wrappers\ldama
llet.py", line 267, in train
    self.convert_input(corpus, infer=False)
  File "C:\Users\biney\Miniconda3\lib\site-packages\gensim\models\wrappers\ldama
llet.py", line 256, in convert_input
    check_output(args=cmd, shell=True)
  File "C:\Users\biney\Miniconda3\lib\site-packages\gensim\utils.py", line 1832,
 in check_output
    raise error
subprocess.CalledProcessError: Command '/c/users/biney/mallet_unzipped/mallet-2.
0.8/bin/mallet import-file --preserve-case --keep-sequence --remove-stopwords --
token-regex "\S+" --input C:\Users\biney\AppData\Local\Temp\e0e83e_corpus.txt --
output C:\Users\biney\AppData\Local\Temp\e0e83e_corpus.mallet' returned non-zero
 exit status 1.
```

I've been bouncing back and forth between these errors and I really don't know what they mean or how to set the right foot forward.  I have tried copying the command shown in the second error message into git bash and it worked without crashing. I had to make adjustments. This command seems to refer to two temporary files that were created prior to me getting the other two error messages I copied and pasted.

`~/mallet_unzipped/mallet-2.0.8/bin/mallet import-file --preserve-case --keep-sequence --remove-stopwords --token-regex "\S+" --input ~/AppData/Local/Temp/a0a87d_corpus.txt --output ~/AppData/Local/Temp/a0a87d_corpus.mallet`

And you may wonder if I tried including `'~'` in the python code... that was the first thing I did, however I got an error message similar to the 2nd one I posted. And I saw prior that error message, another one stating that `'~'` is unrecognized.

Specifying a prefix parameter location seems to always give me an error along the lines of
`FileNotFoundError: [Errno 2] No such file or directory: 'mallet_temp/state.mallet.gz'`
the 'mallet_temp/state.mallet' used the prefix 'mallet_temp'. Any error message I get shows the prefix location and states that no such file or directory exists with the name and extension  shown.

The final attempt I made was the following choices with parameters:

`prefix_path = "/c/users/biney/Projects/twitter_gmu_2018/mallet_temp/"`
`Lda_mallet = LdaMallet(mallet_path="/c/users/biney/mallet_unzipped/mallet-2.0.8/bin/mallet", prefix=prefix_path,  corpus=doc_term_matrix, id2word=doc_dict, iterations=30)`

And I get the following error message

```
Traceback (most recent call last):
  File "text_mining.py", line 634, in <module>
    main()
  File "text_mining.py", line 565, in main
    mallet_LDA_implementation(name_of_lda="mallet_lda_no_filter_t10", create_dic
t=False, remove_low_freq=False)
  File "text_mining.py", line 460, in mallet_LDA_implementation
    Lda_mallet = LdaMallet(mallet_path="/c/users/biney/mallet_unzipped/mallet-2.
0.8/bin/mallet", prefix=prefix_path,  corpus=doc_term_matrix, id2word=doc_dict,
iterations=30)
  File "C:\Users\biney\Miniconda3\lib\site-packages\gensim\models\wrappers\ldama
llet.py", line 126, in __init__
    self.train(corpus)
  File "C:\Users\biney\Miniconda3\lib\site-packages\gensim\models\wrappers\ldama
llet.py", line 267, in train
    self.convert_input(corpus, infer=False)
  File "C:\Users\biney\Miniconda3\lib\site-packages\gensim\models\wrappers\ldama
llet.py", line 242, in convert_input
    with smart_open(self.fcorpustxt(), 'wb') as fout:
  File "C:\Users\biney\Miniconda3\lib\site-packages\smart_open\smart_open_lib.py
", line 181, in smart_open
    fobj = _shortcut_open(uri, mode, **kw)
  File "C:\Users\biney\Miniconda3\lib\site-packages\smart_open\smart_open_lib.py
", line 287, in _shortcut_open
    return io.open(parsed_uri.uri_path, mode, **open_kwargs)
FileNotFoundError: [Errno 2] No such file or directory: '/c/users/biney/Projects
/twitter_gmu_2018/mallet_temp/corpus.txt'
```

What's frustrating from that final error message is that from using file explorer and goingto the /mallet_temp/ directory... there actually is only one file in it called "corpus.txt." So that's suggesting to me that this file is somehow not being found when it should be.

**Comment by Abhishek-Bisht** [comment]
Hi @bbiney1 
In the first case you need to define the OS environment as the below code snippet

```
import os
from gensim.models.wrappers import LdaMallet

os.environ['MALLET_HOME'] = 'C:\\users\\biney\\mallet_unzipped\\mallet-2.0.8'

mallet_path = 'C:\\users\\biney\\mallet_unzipped\\mallet-2.0.8\\bin\\mallet'
ldamallet = LdaMallet(mallet_path,corpus=doc_term_matrix,id2word=doc_dict,iterations=30)
```
It is throwing 'FileNotFoundError' because it is searching for Mallet files it in your base predefined environment.

Hope this helps.

**Comment by fredia** [comment]
hi,I got same question，and I try to set “os.environ['MALLET_HOME']" ,but it did not work.

I use python 3.7(anaconda) on ubuntu18.04.

my output log is:

```
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-43-2e464471d72d> in <module>
----> 1 lda_model = gensim.models.wrappers.LdaMallet(mallet_path,corpus=corpus, num_topics=50,id2word=dictionary,alpha='auto')

~/anaconda3/lib/python3.7/site-packages/gensim/models/wrappers/ldamallet.py in __init__(self, mallet_path, corpus, num_topics, alpha, id2word, workers, prefix, optimize_interval, iterations, topic_threshold, random_seed)
    129         self.random_seed = random_seed
    130         if corpus is not None:
--> 131             self.train(corpus)
    132 
    133     def finferencer(self):

~/anaconda3/lib/python3.7/site-packages/gensim/models/wrappers/ldamallet.py in train(self, corpus)
    283         logger.info("training MALLET LDA with %s", cmd)
    284         check_output(args=cmd, shell=True)
--> 285         self.word_topics = self.load_word_topics()
    286         # NOTE - we are still keeping the wordtopics variable to not break backward compatibility.
    287         # word_topics has replaced wordtopics throughout the code;

~/anaconda3/lib/python3.7/site-packages/gensim/models/wrappers/ldamallet.py in load_word_topics(self)
    341             word2id = revdict(self.id2word)
    342 
--> 343         with utils.open(self.fstate(), 'rb') as fin:
    344             _ = next(fin)  # header
    345             self.alpha = numpy.fromiter(next(fin).split()[2:], dtype=float)

~/anaconda3/lib/python3.7/site-packages/smart_open/smart_open_lib.py in open(uri, mode, buffering, encoding, errors, newline, closefd, opener, ignore_ext, transport_params)
    223     #
    224     binary_mode = _TO_BINARY_LUT.get(mode, mode)
--> 225     binary = _open_binary_stream(uri, binary_mode, transport_params)
    226     if ignore_ext:
    227         decompressed = binary

~/anaconda3/lib/python3.7/site-packages/smart_open/smart_open_lib.py in _open_binary_stream(uri, mode, transport_params)
    399     scheme = _sniff_scheme(uri)
    400     submodule = transport.get_transport(scheme)
--> 401     fobj = submodule.open_uri(uri, mode, transport_params)
    402     if not hasattr(fobj, 'name'):
    403         logger.critical('TODO')

~/anaconda3/lib/python3.7/site-packages/smart_open/local_file.py in open_uri(uri_as_string, mode, transport_params)
     32 def open_uri(uri_as_string, mode, transport_params):
     33     parsed_uri = parse_uri(uri_as_string)
---> 34     fobj = io.open(parsed_uri['uri_path'], mode)
     35     return fobj
     36 

FileNotFoundError: [Errno 2] No such file or directory: '/tmp/7d63c5_state.mallet.gz'

```
but I find  7d63c5_corpus.mallet and 7d63c5_corpus.txt in '/tmp':
![image](https://user-images.githubusercontent.com/18653940/92483540-8190a300-f21b-11ea-9a58-b6b368d931bc.png)

how should I solve it?
