### ISSUE TITLE
Getting state from infer-topics

### ISSUE THREAD

**Issue by ezubaric** [mimno/Mallet#137]
It doesn't seem possible to get topic assignments when inferring topics.

```
> Exception in thread "main" java.lang.IllegalArgumentException: Unrecognized option 6: --output-state
>         at cc.mallet.util.CommandOption$List.process(CommandOption.java:345)
>         at cc.mallet.util.CommandOption.process(CommandOption.java:146)
>         at cc.mallet.topics.tui.InferTopics.main(InferTopics.java:60)
```

Is this a bug or expected behavior?

**Comment by aimiyu** [comment]
When I run 
`bin/mallet  infer-topics --help`
It seems there's no option "--output-state"

But it has "inferencer"  ， gets from “--inferencer-filenam” when running “train-topics”

**Comment by ezubaric** [comment]
But isn't the --inferencer-filename the filename for the input *model*, not the topic states?  Let me know if I'm missing something.

**Comment by aimiyu** [comment]
The option should be "--input-state" instead of "--output-state",if you want to use the states file. But I also found there is no such option for the mallet/infer-topics.

**Comment by mimno** [comment]
This is not currently implemented, but shouldn't be hard to add. Here's what I would expect a new "--output-state" option to do:

Currently the inferencer updates the average topic-token count for each document every "--sample-interval" iterations, for a total of "--num-iterations" iterations. By default this happens 10 times, with 10 iterations between each sample.

NEW: When this saved iteration happens, if the "--output-state" option is not null, we save the current sampling state, in the standard space-delimited state-file format, for just the new documents (NOT the training documents), with a filename equal to the provided string plus an iteration number. For example, with "--output-state state.gz", this would create state.gz.10, state.gz.20, ..., state.gz.100.

Sound good?

**Comment by ezubaric** [comment]
Sounds perfect, thanks!
