### ISSUE TITLE
ClassCastException when training classifier

### ISSUE THREAD

**Issue by SeaCelo** [mimno/Mallet#150]
I'm following the steps here: http://mallet.cs.umass.edu/classification.php

Running on Mac (Mojave). Mallet 2.0.8
Trying to train a classifier. 
mallet train-classifier --input ~/test/sdg-classifier.mallet --output-classifier ~/test/sdg.classifier --trainer MaxEnt --training-portion 0.9

Throws a ClassCastException Error. Trace:

Trial 0 Training MaxEntTrainer,gaussianPriorVariance=1.0 with 15 instances
Exception in thread "main" java.lang.ClassCastException: class cc.mallet.types.FeatureSequenceWithBigrams cannot be cast to class cc.mallet.types.FeatureVector (cc.mallet.types.FeatureSequenceWithBigrams and cc.mallet.types.FeatureVector are in unnamed module of loader 'app')
	at cc.mallet.classify.MaxEntOptimizableByLabelLikelihood.<init>(MaxEntOptimizableByLabelLikelihood.java:109)
	at cc.mallet.classify.MaxEntTrainer.getOptimizable(MaxEntTrainer.java:142)
	at cc.mallet.classify.MaxEntTrainer.getOptimizable(MaxEntTrainer.java:131)
	at cc.mallet.classify.MaxEntTrainer.getOptimizer(MaxEntTrainer.java:185)
	at cc.mallet.classify.MaxEntTrainer.train(MaxEntTrainer.java:248)
	at cc.mallet.classify.MaxEntTrainer.train(MaxEntTrainer.java:242)
	at cc.mallet.classify.MaxEntTrainer.train(MaxEntTrainer.java:52)
	at cc.mallet.classify.tui.Vectors2Classify.main(Vectors2Classify.java:431)

**Comment by SeaCelo** [comment]
Cannot reproduce
