### ISSUE TITLE
Unsupervised learning using K-Means is not usable

### ISSUE THREAD

**Issue by mommi84** [mimno/Mallet#16]
Since unsupervised learning does not need labels, I suppose that all instances shall be contained in a single cluster before being parsed. Unfortunately, calling Clusterings2Clusterings generates the following exception:

```
$ java -cp dist/*:lib/* cc.mallet.cluster.tui.Clusterings2Clusterings --input text.clusterings --training-proportion 0.5 --output-prefix text.clusterings
number clusterings=1
Exception in thread "main" java.lang.IllegalArgumentException: Number of labels must be strictly positive.
    at cc.mallet.cluster.Clustering.<init>(Clustering.java:41)
    at cc.mallet.cluster.util.ClusterUtils.createSingletonClustering(ClusterUtils.java:107)
    at cc.mallet.cluster.tui.Clusterings2Clusterings.createSmallerClustering(Clusterings2Clusterings.java:141)
    at cc.mallet.cluster.tui.Clusterings2Clusterings.main(Clusterings2Clusterings.java:118)
```

**Comment by Eupraxis** [comment]
Why not give them all the same "default" label? Then the number of labels will be 1>0. Would that work?

**Comment by mommi84** [comment]
In this example, every file represents an instance. The label of an instance is the folder (or clustering) where the file is located, therefore they all already had the same "default" label.
