### ISSUE TITLE
Failing tests

### ISSUE THREAD

**Issue by carschno** [mimno/Mallet#22]
There are multiple unit tests that fail. They seem to have different roots and therefore will presumably require multiple issues, but I'll begin here with an enumeration.
* multiple in `cc.mallet.extract.test`: if you use a localization that uses different number formatting (e.g. `,` instead of `.` in decimal numbers, the string comparisons fail.
* various in `cc.mallet.pipe.tests.TestSpacePipe`
* various in `cc.mallet.fst.tests`
* various in `cc.mallet.grmm.test`

Can anyone confirm these failures? Apart from the localization issues, there are cases in which actual values clearly differ from expected results.

**Comment by alansaid** [comment]
I can confirm this. It seems that a few of the ```expectedXml``` variables in ```TestDocumentExtraction```are incorrect (?).

Also, I am getting the following error:
```
java.lang.IllegalStateException: Instance is locked.
	at cc.mallet.types.Instance.setData(Instance.java:146)
	at cc.mallet.pipe.CharSequence2TokenSequence.pipe(CharSequence2TokenSequence.java:70)
	at cc.mallet.pipe.Pipe$SimplePipeInstanceIterator.next(Pipe.java:295)
	at cc.mallet.pipe.Pipe$SimplePipeInstanceIterator.next(Pipe.java:283)
	at cc.mallet.pipe.Pipe$SimplePipeInstanceIterator.next(Pipe.java:291)
	at cc.mallet.pipe.Pipe$SimplePipeInstanceIterator.next(Pipe.java:283)
	at cc.mallet.pipe.Pipe$SimplePipeInstanceIterator.next(Pipe.java:291)
	at cc.mallet.pipe.Pipe$SimplePipeInstanceIterator.next(Pipe.java:283)
	at cc.mallet.pipe.Pipe$SimplePipeInstanceIterator.next(Pipe.java:291)
	at cc.mallet.pipe.Pipe$SimplePipeInstanceIterator.next(Pipe.java:283)
	at cc.mallet.pipe.Pipe$SimplePipeInstanceIterator.next(Pipe.java:291)
	at cc.mallet.pipe.Pipe$SimplePipeInstanceIterator.next(Pipe.java:283)
	at cc.mallet.pipe.Pipe$SimplePipeInstanceIterator.next(Pipe.java:291)
	at cc.mallet.pipe.Pipe$SimplePipeInstanceIterator.next(Pipe.java:283)
	at cc.mallet.types.InstanceList.addThruPipe(InstanceList.java:267)
	at cc.mallet.extract.CRFExtractor.extract(CRFExtractor.java:153)
	at cc.mallet.extract.test.TestDocumentViewer.testSpaceViewer(TestDocumentViewer.java:63)
...
...
..

```
Provided I have understood the code correctly, it appears that the method ```public Instance pipe (Instance carrier)``` in ```CharSequence2TokenSequence```is attempting to alter an ```Instance``` in an ```InstanceList``` after it has been locked.

**Comment by alansaid** [comment]
__NB__ this is when building with Maven, i.e. issuing ```mvn clean install``` 
Building with ant (```ant compile``` etc.) the build passes without failures (except when tests are issued).
