### ISSUE TITLE
java.lang.ClassCastException processing japanese data

### ISSUE THREAD

**Issue by craigpfeifer** [mimno/Mallet#29]
While trying to build a LDA model from japanese docs, using the following cmd line:

     Mallet/bin/mallet train-topics --num-topics 5 --input text.vectors --num-threads 4 --optimize-interval 1 --num-iterations 1500 --output-model mymodel.model --evaluator-filename myevali.eval --diagnostics-file diagnostics.txt --num-top-words 5000 --output-topic-keys TOPIC_KEYS.txt --topic-word-weights-file TOPIC_WORD_WEIGHTS.txt --xml-topic-phrase-report XML_TOPIC_PHRASE_REPORT.txt --output-topic-docs TOPIC_DOCS.txt

I get the stack trace:
Exception in thread "main" java.lang.ClassCastException: java.net.URI cannot be cast to java.lang.String
	at cc.mallet.topics.ParallelTopicModel.printTopicDocuments(ParallelTopicModel.java:1748)
	at cc.mallet.topics.tui.TopicTrainer.main(TopicTrainer.java:281)

Thoughts?

**Comment by craigpfeifer** [comment]
Upon further review, the file names are URIs:
file:/Users/fofoo/data/project/data/jp/text-jp/xyzzy.pdf.txt

So simply tweaking line 1478 to:
String name = data.get(doc).instance.getName().toString();

from 
String name = (String) data.get(doc).instance.getName();

Solved my problem

**Comment by astvansh** [comment]
Craig: can you please advise me on how you built ParallelTopicModel.java to get the new mallet executable? Thank you.

**Comment by craigpfeifer** [comment]
Sorry, this was a while ago, and I don't have the code I used. I think I made the change in the source and then re built via ant or maven?
