### ISSUE TITLE
2.0.8RC3 Incremental training exception

### ISSUE THREAD

**Issue by janrygl** [mimno/Mallet#50]
I am trying to use incremental mallet (2.0.8RC3) training as described in http://comments.gmane.org/gmane.comp.ai.mallet.devel/2153

I tried different input data, but in all cases except the case in which I incrementally train with the data already used for the first training,  I get following exception:

```
Total time: 40 seconds
Topic Evaluator: 100 topics, 7 topic bits, 1111111 topic mask
 Rewriting extended pipe from /mnt/work/data/docs/t1/test_corpus.mallet
  Instance ID = ca0786a3409cc2fb:aba8caa:152ab48f2dc:-7ffa
max tokens: 669
total tokens: 565287
Data loaded.
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 14386
	at cc.mallet.topics.ParallelTopicModel.buildInitialTypeTopicCounts(ParallelTopicModel.java:333)
	at cc.mallet.topics.ParallelTopicModel.addInstances(ParallelTopicModel.java:256)
	at cc.mallet.topics.tui.TopicTrainer.main(TopicTrainer.java:218)
```

I enclose my train script and there are also attached input text corpora. I am using Linux mint.
```
#!/bin/sh
# update paths for your mallet bin and data folder (where new folders can be created)
export doc_path='/mnt/work/data/docs';
export mallet_bin='/software/mallet-2.0.8RC3/bin/mallet';
export text_corpus1='/mnt/work/data/docs/textcorpus1.txt';
export text_corpus2='/mnt/work/data/docs/textcorpus2.txt';

mkdir -p ${doc_path}/t1
mkdir -p ${doc_path}/t2

# Preparing data:

${mallet_bin} import-file --preserve-case --keep-sequence --remove-stopwords --token-regex '\S+' --input ${text_corpus1} --output ${doc_path}/t1/test_corpus.mallet

# Training a model:

${mallet_bin} train-topics --input ${doc_path}/t1/test_corpus.mallet --num-topics 100 --optimize-interval 10 --num-threads 11 --output-state ${doc_path}/t1/test_state.mallet.gz --output-doc-topics ${doc_path}/t1/adoctopics.txt --output-topic-keys ${doc_path}/t1/atopickeys.txt --num-iterations 1000 --inferencer-filename ${doc_path}/t1/test_inferencer.mallet --evaluator-filename e.eval --optimize-burn-in 100 --random-seed 1 --output-model ${doc_path}/t1/test_mallet_model



# Preparing data using previous pipe + incremental training using previous corpus.mallet:

${mallet_bin} import-file --preserve-case --keep-sequence --remove-stopwords --token-regex '\S+' --input ${text_corpus2} --output ${doc_path}/t2/test_corpus.mallet --use-pipe-from ${doc_path}/t1/test_corpus.mallet

# This line will raise the exception:
${mallet_bin} train-topics --input ${doc_path}/t2/test_corpus.mallet --num-topics 100 --optimize-interval 10 --num-threads 11 --output-state ${doc_path}/t2/test_state.mallet.gz --output-doc-topics ${doc_path}/t2/adoctopics.txt --output-topic-keys ${doc_path}/t2/atopickeys.txt --num-iterations 1000 --inferencer-filename ${doc_path}/t2/test_inferencer.mallet --evaluator-filename e.eval --optimize-burn-in 100 --random-seed 1 --output-model ${doc_path}/t2/test_mallet_model --input-model ${doc_path}/t1/test_mallet_model
```
[textcorpus1.txt](https://github.com/mimno/Mallet/files/117076/textcorpus1.txt)
[textcorpus2.txt](https://github.com/mimno/Mallet/files/117077/textcorpus2.txt)

Thank you for your help and great library.

**Comment by piskvorky** [comment]
@janrygl also ask at the mailing list; more people follow that compared to github. Perhaps someone has tried/resolved this, or can give advice.

**Comment by victorlaerte** [comment]
Any updates on this @janrygl ?
