### ISSUE TITLE
ClassCastException with writing top documents per topics

### ISSUE THREAD

**Issue by audenaert** [mimno/Mallet#51]
I am encountering the following ClassCastException when I try to write the top document/topic to a file.

```
Exception in thread "main" java.lang.ClassCastException: java.net.URI cannot be cast to java.lang.String
        at cc.mallet.topics.ParallelTopicModel.printTopicDocuments(ParallelTopicModel.java:1773)
        at cc.mallet.topics.tui.TopicTrainer.main(TopicTrainer.java:281)
```

*Steps to Reproduce*
The following command will reproduce the error ([ap.zip](https://github.com/mimno/Mallet/files/119197/ap.zip) contains the imported feature vectors from the AP dataset):

`mallet train-topics --input ap.vectors --num-topics 20 --output-topic-docs error.txt`

*Solution*
The following patch fixes the problem. I will submit a pull request shortly.

```
diff --git a/src/cc/mallet/topics/ParallelTopicModel.java b/src/cc/mallet/topics/ParallelTopicModel.java
index 287ead6..f9d1317 100644
--- a/src/cc/mallet/topics/ParallelTopicModel.java
+++ b/src/cc/mallet/topics/ParallelTopicModel.java
@@ -1770,11 +1770,11 @@
 				
 				int doc = sorter.getID();
 				double proportion = sorter.getWeight();
-				String name = (String) data.get(doc).instance.getName();
+				Object name = data.get(doc).instance.getName();
 				if (name == null) {
 					name = "no-name";
 				}
-				out.format("%d %d %s %f\n", topic, doc, name, proportion);
+				out.format("%d %d %s %f\n", topic, doc, name.toString(), proportion);
 				
 				i++;
 			}
```

**Comment by astvansh** [comment]
I have also run into this error message with mallet-2.0.8RC3. Do we have a downloadable MALLET that I can install and proceed without this error?

**Comment by carschno** [comment]
v2.0.8 has been released a while ago. I think it is accessible through Maven central. Find the source code here: https://github.com/mimno/Mallet/tree/v2.0.8
I have no idea though whether that patch has been included.
