### ISSUE TITLE
HierarchicalLDA class cast exception

### ISSUE THREAD

**Issue by mihaiiancu** [mimno/Mallet#93]
The following exception is thrown when trying to run HierarchicalLDATUI with proper arguments:
--
Exception in thread "main" java.lang.ClassCastException: [Ljava.lang.Object; cannot be cast to [Lcc.mallet.topics.HierarchicalLDA$NCRPNode;
	at cc.mallet.topics.HierarchicalLDA.samplePath(HierarchicalLDA.java:230)
	at cc.mallet.topics.HierarchicalLDA.estimate(HierarchicalLDA.java:135)
	at cc.mallet.topics.tui.HierarchicalLDATUI.main(HierarchicalLDATUI.java:109)
--

**Comment by mihaiiancu** [comment]
pull request accepted and merged to master
