### ISSUE TITLE
Error in optimizeBeta function

### ISSUE THREAD

**Issue by julianmaster** [mimno/Mallet#98]
Hello,
I have an issue sometimes when I running ParallelTopicModel.

```
Caused by: java.lang.ArrayIndexOutOfBoundsException: 2214800
        at cc.mallet.topics.ParallelTopicModel.optimizeBeta(ParallelTopicModel.java:675)
        at cc.mallet.topics.ParallelTopicModel.estimate(ParallelTopicModel.java:901)
        at main.LDAManager.runLDA(LDAManager.java:136)
        at main.LDAManager.runLDA(LDAManager.java:102)
        at main.LDAManager.createNewLDA(LDAManager.java:53)
        ... 8 more
```
Do you have a solution ?

Thanks!

**Comment by mimno** [comment]
It looks like this would happen if there is a word type ID larger than the alphabet size. The `numTypes` variable is set when you call `addInstances()`. Are you doing something that would change the vocabulary after adding training data, or adding multiple instance lists?
